spring:
  r2dbc:
    url: r2dbc:h2:mem:///eshop;DB_CLOSE_DELAY=-1
    username: sa
    password:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:eshop;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password:

client:
  payment-service:
    base-url: "http://localhost:8081/payment-service/buy?cartId"
    connect-timeout-ms: 1000
    response-timeout-ms: 1000